name: legendary_money_hardcore
version: '1.0.0'
main: www.legendarycommunity.com.br.legendary_money_hardcore.Legendary_money_hardcore
api-version: '1.21'
authors: [ Thaynison ]
description: Plugin Legendary Community
website: http://www.legendarycommunity.com.br
depend:
  - Vault
commands:
  bankhardcore:
    description: Banco do Hardcore
    usage: /bankhardcore <nome_do_jogador>
    permission: bankhardcore.open
  banknidavellir:
    description: Banco do Nidavellir
    usage: /banknidavellir <nome_do_jogador>
    permission: banknidavellir.open
  banktokens:
    description: Banco do Tokens
    usage: /banktokens <nome_do_jogador>
    permission: banktokens.open